config/routes.rb
Rails.application.routes.draw do
root 'doctors#index'

resources :patients
resources :doctors do
  resources :appointments, only: [:index, :new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
  
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :patients, through: :appointments

end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :doctors, through: :appointmemts

  def full_name
    "#{self.first_name} #{self.last_name}"

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_doctor

  def index
    @walkin = @doctor.appointments.where(appoint: 'walkin')
    @urgent = @doctor.appointments.where(appoint: 'urgent')
  end

  def new
    @patients = Patient.all - @doctor.patients
    @appointment = @doctor.appointments.new
  end

  def create
    @appointment = @doctor.appointments.new(appointment_params)
    if @appointment.save
      redirect_to doctor_appointments_path(@doctor)
    else
      render :new
    end
  end
  def destroy
    @apointment.destroy
    render :new

  end

  private
  def set_doctor
    @doctor = Doctor.find(params[:doctor_id])
  end
  def appointment_params
    params.require(:appointment).permit(:appoint, :patient_id)

  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor,  only: [:show, :edit,:update, :destroy]
  def index
    @doctors = Doctor.all
  end

  def show
  end

  def new
    @doctor = Doctor.new
  end
  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to doctors_path(@doctor)
    else
      render :new
    end
  end
  def destroy
    @doctor.destroy
    redirect_to doctors_path
  end
  def update
    if @doctor.update(doctor_params)
      redirect_to doctor_path
    else
      render :edit
    end
  end
  private
  def set_doctor
    @doctor = Doctor.find(params[:id])
  end
  def doctor_params
    params.require(:doctor).permit(:name)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :destroy, :update]


  def index
    @patients = Patient.all
  end

  def show
  end

  def new
    @patient = Patient.new
  end
  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to patients_path(@patient)
    else
      render :new
    end
  end
  def destroy
    @patient.destroy
    redirect_to patients_path
  end

    def update
      if @patient.update(patient_params)
        redirect_to patient_path
      else
        render :edit
      end
    end


  private
  def set_patient
    @patient = Patient.find(params[:id])
  end
  def patient_params
    params.require(:patient).permit(:first_name, :last_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/index.html.erb
<h1><%= @doctor.name %>: Appointments</h1>
<%= link_to 'Add Appointment', new_doctor_appointment_path(@doctor) %>
<br>

<h2>walkin</h2>
<ul>
  <% @walkin.each do |walkin| %>
  <li>
    <%= walkin.patient.full_name %>
    <br>
    <%= link_to 'Remove', doctor_appointment_path(@doctor, walkin), method: :delete %>
  </li>
  <% end %>
</ul>

<h2>urgent</h2>
<ul>
  <% @urgent.each do |urgent| %>
  <li>
    <%= urgent.patient.full_name %>
    <br>
    <%= link_to 'Remove', doctor_appointment_path(@doctor, urgent), method: :delete %>
  </li>
  <% end %>
</ul>

app/views/appointments/new.html.erb
<h1>Add Appointments</h1>

<%= form_with(model: [@doctor, @appointment], local: true, class: "ui form" ) do |f| %>

<%= f.label :patient %>

<%= f.select :patient_id, @patients.collect { |u| [u.full_name, u.id] } %>
<br>
<%= f.label :appoint %>
<%= f.select :appoint, ['walkin', 'urgent'] %>
<br>
<%= f.submit nil, class: "ui green button inverted" %>
<% end %>

app/views/doctors/edit.html.erb
<h1>edit your doctor</h1>

<%= form_with(model: @doctor, local: true, class: "ui form") do |f| %>
<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name, required: true, placeholder: "Doctor Name" %>
</div>
<%= f.submit  %>
<% end %>

app/views/doctors/index.html.erb
<h1>Doctors</h1>
<br />


<ul>
  <% @doctors.each do |doctor| %>
  <li>
    <%= link_to doctor.name, doctor_path(doctor) %>
  </li>
  <% end %>
</ul>

app/views/doctors/new.html.erb
<h1>Become a doctor at our hospital</h1>

<%= form_with(model: @doctor, local: true, class: "ui form") do |f| %>
<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name, required: true, placeholder: "Doctor Name" %>
</div>
<%= f.submit  %>
<% end %>

app/views/doctors/show.html.erb
<h1><%= @doctor.name %></h1>
<br>
<%= link_to 'Delete Doctor', doctor_path, method: :delete, class: "ui red button inverted" %>
<%= link_to 'Edit Doctor', edit_doctor_path(@doctor), class: "ui green button" %>
<br>
<br>
<br>
<%= link_to 'appointments', doctor_appointments_path(@doctor), class: "ui primary button inverted" %>

app/views/layouts/_navbar.html.erb
<nav>
  <ul>
    <li>
      <%= link_to 'doctor', doctors_path %>
    </li>
    <li>
      <%= link_to 'Add doctor', new_doctor_path %>
    </li>
    <li>
      <%= link_to 'patient', patients_path %>
    </li>
    <li>
      <%= link_to 'Add patient', new_patient_path %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hospital</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/patients/edit.html.erb
<h1>edit patient</h1>

<%= form_with(model: @patient, local: true, class: "ui form") do |f| %>
<div class="field">
  <%= f.label :first_name %>
  <%= f.text_field :first_name, required: true, placeholder: "first Name" %>
</div>
<div class="field">
  <%= f.label :last_name %>
  <%= f.text_field :last_name, required: true, placeholder: "last Name" %>
</div>
<%= f.submit  %>
<% end %>

app/views/patients/index.html.erb
<h1>Patients</h1>


<ul>
  <% @patients.each do |patient| %>
  <li>
  <%= link_to patient.full_name, patient_path(patient) %>
  </li>
  <% end %>
</ul>

app/views/patients/new.html.erb
<h1>register as a Patient</h1>

<%= form_with(model: @patient, local: true, class: 'ui form') do |f| %>
<div class="field">
  <%= f.label :first_name %>
  <%= f.text_field :first_name, required: true, placeholder: "First Name" %>
</div>

<div class="field">
  <%= f.label :last_name %>
  <%= f.text_field :last_name, required: true, placeholder: "Last Name" %>
</div>
<%= f.submit %>
<% end %>

app/views/patients/show.html.erb
<h1><%= @patient.full_name %></h1>
<hr />
<%= link_to 'Delete patient', @patient, method: :delete, class: "ui red button inverted" %>
<%= link_to 'Edit patient', edit_patient_path(@patient), class: "ui green button" %>